### PR TITLE
Update NgRx Integration example

### PR DESCRIPTION
**Pull request by timdeschryver**
- Links pointing to the docs website
- Update implementation to complement new NgRx versions

### CODE REVIEW

**Comment by zalmoxisus** [comment]
Thanks! Do you know if [Book Collection demo link](http://ngrx.github.io/example-app/) specified there and in [README](https://github.com/zalmoxisus/redux-devtools-extension#demo) is up to date? According to https://github.com/zalmoxisus/redux-devtools-extension/issues/589#issuecomment-442410276 it's not.

Would be great to provide a demo so we could probably add it in e2e tests in future to avoid regressions for ngrx. I guess after Redux, NgRx is the most popular library using our extension, so it would deserve some tests.

**Comment by timdeschryver** [comment]
We got a new example at https://ngrx.github.io/platform/example-app/#/login but requires a login (username: test, password: doesn't matter). That's why I've left the old example app. I do agree that it would be better to have the new one, I'll add an extra commit with these changes.

**Comment by zalmoxisus** [comment]
@timdeschryver looks like the new demo has some issues using the extension. Nothing appears on the extension's side.

**Comment by timdeschryver** [comment]
🤦‍♂️ you're right, thanks for noticing it!
The example app is also already a year old. Give me some time and I'll see what I can do in order to have the example app updated, with the extension on 😄

**Comment by zalmoxisus** [comment]
No rush, thanks for working on that.

**Comment by zalmoxisus** [comment]
Thanks again for the contribution! I've started a complete rewrite of the extension for `3.0`, then will add proper e2e tests for ngrx.

**Comment by timdeschryver** [comment]
Sounds great!

**Pull request merged**
