### PR TITLE
Use non oppressive language

### PR DESCRIPTION
**Pull request by martymclaugh**
change whitelist terms to allowList and blacklist to blockList

### CODE REVIEW

**Comment by bdurrer** [comment]
renaming parameters of libraries with 750k downloads per week is a stupid idea, regardless of intention

**Comment by david-shortman** [comment]
> renaming parameters of libraries with 750k downloads per week is a stupid idea, regardless of intention

Making breaking changes to libraries is highly inconvenient, sure. Calling this idea stupid regardless of intention sounds unnecessarily hostile to me.

@martymclaugh, what if this PR introduces the replacements terms as a non-breaking change, where the documentation only refers to the new terms, and both the new and old terms work, but the old are marked deprecated?

**Comment by david-shortman** [comment]
Also, `denylist` appears to be the more popular term, so I recommend using that term instead of `blocklist`:
https://trends.google.com/trends/explore?geo=US&q=blocklist,denylist

**Comment by zgavin1** [comment]
bump

**Comment by Methuselah96** [comment]
Resolved in https://github.com/reduxjs/redux-devtools/pull/851.

**Pull request closed without merging**
