### PR TITLE
Add support for Redux 4.x

### PR DESCRIPTION
**Pull request by ApacheEx**
Redux 4 is out: https://github.com/reactjs/redux/releases/tag/v4.0.0

I didn't notice any breaking changes. 💯
~I have also moved some packages to `peerDependencies`, it allows to reduce bundle size and let user to choose which version of package use.~

am I missed something?

### CODE REVIEW

**Comment by jacoporicare** [comment]
I assume it's important to update `npm-package/package.json`. At least this is the version of `package.json` I have in my project when I installed `redux-devtools-extension`. Can you please add Redux 4 there as well?

**Comment by ApacheEx** [comment]
@jacoporicare,
thanks for info. Does it mean we need only update `./npm-package/package.json` and keep `./package.json` as-is?

**Comment by jacoporicare** [comment]
Unfortunately I'm not a maintainer and I don't know what's the purpose of the `package.json` in the root 🙁... I just upgraded Redux to v4 in my project and noticed that peer deps are not matching so I wanted to do a PR to fix it and found yours 👍.

**Comment by ApacheEx** [comment]
let's wait for maintainer decision 👌

**Comment by nickmccurdy** [comment]
I like this change overall and using peerDependencies on the root package is a great idea, but shouldn't `react-dom` be a production dependency since it's used to render the extension? https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/options/index.js

**Comment by nickmccurdy** [comment]
Sorry if I was being misleading, I was referring to react-dom being in devDependencies but not peerDependencies. This means npm won't ensure react-dom is installed when this is used as a dependency of another package, which I think would break it because it's used to render the extension, not just in tests. We should add react-dom to peerDependencies or dependencies (probably the latter if it doesn't matter what version of react-dom is used by the underlying app).

**Comment by nickmccurdy** [comment]
Cool thanks for making this consistent. I'm having second thoughts about if these need to be peer dependencies though. The redux-devtools-extension has a peer dependency on redux because it's used directly with an existing Redux app, which makes sense. However aren't the dependencies in the root package isolated to the extension (in which case they should probably not be peer dependencies)? If that's the case, it may be better to only use peer dependencies in redux-devtools-extension as we were before, which would involve reverting these changes to remotedev-redux-devtools-extension's package.json.

**Comment by ApacheEx** [comment]
@nickmccurdy - yeah now I think we need to change only `./npm-package/package.json`, will make change

**Comment by jacoporicare** [comment]
@nickmccurdy That’s exactly what I was trying to say 😉.

**Comment by markerikson** [comment]
There does appear to be an incompatibility with Redux 4 that needs to be fixed - this line is out of date:

https://github.com/zalmoxisus/redux-devtools-extension/blob/bc4baef181bd87b4e118bb764b440eddb769e677/src/app/service/Monitor.js#L26

See https://github.com/reactjs/redux/issues/2943 for discussion.

**Comment by nickmccurdy** [comment]
Good catch, it's now a string starting with `@@redux/INIT` and some random stuff appended right? Should we match the start of the string or is there a better way?

**Comment by ApacheEx** [comment]
seems we should not import actionTypes from redux. Just match the start of the string will work as expected.

**Comment by kanzelm3** [comment]
Any ETA on when this will be merged?

**Comment by kaiwa** [comment]
I just spent a reasonable amount of time figuring out why my app was broken, until I got that it is because of this issue. Please merge this.

**Comment by Dabolus** [comment]
@nickmccurdy just to answer you question: [yes, it is a string with `@@redux/INIT` and some random stuff appended](https://github.com/reduxjs/redux/blob/9b43c56b98cc75505e161b8e26c18240fa99b184/src/utils/actionTypes.js#L16). The random stuff is computed by [generating a random number and doing some operations on it](https://github.com/reduxjs/redux/blob/9b43c56b98cc75505e161b8e26c18240fa99b184/src/utils/actionTypes.js#L8). The random stuff can range from not existing (when the random number is zero) to being 31 characters long. Since it is a dot separated base36 string, we are certain that it can only contain letters from a to z, numbers from 0 to 9 and dots.

To sum everything up, it is possible to use a regex such as:
`/^@@redux\/INIT[a-z0-9.]{0,31}$/`

Instead of using `indexOf`, but I'm quite sure the best option would be to keep using `indexOf` for multiple reasons (i.e. performance and possibly future compatibility in case the way the random string is computed changes)

**Comment by kanzelm3** [comment]
Is this project still being actively maintained?

**Comment by kanzelm3** [comment]
@nickmccurdy @zalmoxisus I apologize in advance for the spam, but this is still an issue in the v2.15.2 release of the Redux DevTools extension. Considering it's been approved and CI passed, I was hoping this would have been merged weeks ago.

I really don't want to have to implement an alternative solution, because I think this extension is great. Please merge and release this fix!

**Comment by kanzelm3** [comment]
To be clear, my project is using `composeWithDevTools` from the [instructions outlined here](https://github.com/zalmoxisus/redux-devtools-extension#13-use-redux-devtools-extension-package-from-npm). While I have v2.15.2 of the browser extension installed, the latest version of `redux-devtools-extension` available on npm is v2.13.2.

**Comment by solshark** [comment]
I know it’s not optimal but meanwhile you could use this fork: https://www.npmjs.com/package/redux-devtools-extension-sol

**Comment by giopunt** [comment]
@nickmccurdy any update on this?

**Comment by asos-giovannip** [comment]
Do we need another PR to bump the version and/or publish to npm?

@nickmccurdy @zalmoxisus

**Comment by jhen0409** [comment]
Published the npm package as `v2.13.3`. For chrome extension publish will be later.

**Comment by bbthorntz** [comment]
It seems like there are still issues when using `store.replaceReducers`. Redux will now dispatch a [`@@redux/REPLACE`](https://github.com/reduxjs/redux/blob/9b43c56b98cc75505e161b8e26c18240fa99b184/src/utils/actionTypes.js) action rather than the previous `@@redux/INIT` action.

https://github.com/reduxjs/redux/issues/2943

**Comment by deb0rian** [comment]
Having this during any build process with yarn:
`warning " > redux-devtools@3.4.1" has incorrect peer dependency "redux@^3.5.2".`

**Comment by nickmccurdy** [comment]
It seems like the Firefox extension hasn't been updated.

**Pull request merged**
