### PR TITLE
Fix codemirror style for TestGenerator

### PR DESCRIPTION
**Pull request by jhen0409**

### CODE REVIEW

**Comment by jhen0409** [comment]
But it doesn't completely solve the problem, if Inspector layout is Up-Down mode:



So I make https://github.com/alexkuz/redux-devtools-inspector/pull/46.

**Comment by zalmoxisus** [comment]
@jhen0409, thanks a lot for working on this! The funny part is that I was using the same workaround (and yes it worked only in the first case), but removed it in https://github.com/zalmoxisus/redux-devtools-extension/commit/ac998ccda4d5f1efb770d72a7fb6bc165a747cc2 as for some reason it was freezing the browser when the window is too small (strangely this bug appeared with Chorome 42).

Better to address it in the Inspector Monitor, making the inner part scrollable and the toolbar fixed on the top, which is a problem not only for custom components.

**Comment by zalmoxisus** [comment]
It still hangs the browser in the latest Chrome, though fixed in Canary. To reproduce, make the window small and click the `Test` tab.

**Comment by jhen0409** [comment]
@zalmoxisus, ok. :D Just checkout alexkuz/redux-devtools-inspector#46, it should can be solved the problem.

**Pull request closed without merging**
